name: CI Build

on: [push, pull_request]

jobs:
  win32:
    name: "Build Win32 Installer"
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main
      - run: npm ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run parcel-build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run electron-build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        name: Upload Windows Installer
        with:
          name: twinkle-tray-exe-${{ steps.info.outputs.version }}-${{ github.sha }}
          path: dist/*.exe
  appx:
    name: "Build AppX Packages"
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main
      - run: npm ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run appx
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        name: Upload x64 AppX
        with:
          name: twinkle-tray-appx-x64-${{ steps.info.outputs.version }}-${{ github.sha }}
          path: dist/*-store.appx
      - run: npm run appx-arm64
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        name: Upload ARM64 AppX
        with:
          name: twinkle-tray-appx-arm64-${{ steps.info.outputs.version }}-${{ github.sha }}
          path: dist/*-store-arm64.appx
